name: Hello World & Send Email on Push

on:
  push:
    branches:
      - main

jobs:
  say-hello:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Print Hello World message
        run: echo "Hello, World!"

  send-email:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Send Email via Mailtrap
        env:
          MAILTRAP_USERNAME: 'a6928cec736af1'
          MAILTRAP_PASSWORD: '967757816e8c37'
          MAILTRAP_HOST: 'sandbox.smtp.mailtrap.io'
          MAILTRAP_PORT: '25'
        run: |
          echo "Sending email via Mailtrap"
          apt-get update && apt-get install -y ssmtp
          echo "root=postmaster" > /etc/ssmtp/ssmtp.conf
          echo "mailhub=$MAILTRAP_HOST:$MAILTRAP_PORT" >> /etc/ssmtp/ssmtp.conf
          echo "AuthUser=$MAILTRAP_USERNAME" >> /etc/ssmtp/ssmtp.conf
          echo "AuthPass=$MAILTRAP_PASSWORD" >> /etc/ssmtp/ssmtp.conf
          echo "UseTLS=YES" >> /etc/ssmtp/ssmtp.conf
          echo "UseSTARTTLS=YES" >> /etc/ssmtp/ssmtp.conf
          echo "From: sender@example.com" > /tmp/email.txt
          echo "To: recipient@example.com" >> /tmp/email.txt
          echo "Subject: New Push Notification" >> /tmp/email.txt
          echo "A new push has been made to the repository!" >> /tmp/email.txt
          ssmtp recipient@example.com < /tmp/email.txt
