name: Send Email

on:
  push:
    branches:
      - main

jobs:
  send_email:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'  

    - name: Install Nodemailer
      run: npm install nodemailer

    - name: Send Email with Nodemailer
      env:
        MAILTRAP_USERNAME: ${{ secrets.MAILTRAP_USERNAME }}
        MAILTRAP_PASSWORD: ${{ secrets.MAILTRAP_PASSWORD }}
        MAILTRAP_HOST: sandbox.smtp.mailtrap.io
        MAILTRAP_PORT: 2525
        GITHUB_COMMIT_MESSAGE: ${{ github.event.head_commit.message }}  # Capture the commit message

      run: |
        node -e "
        const nodemailer = require('nodemailer');
        let transporter = nodemailer.createTransport({
          host: process.env.MAILTRAP_HOST,
          port: process.env.MAILTRAP_PORT,
          auth: {
            user: process.env.MAILTRAP_USERNAME,
            pass: process.env.MAILTRAP_PASSWORD
          }
        });
          console.log('commit');
          console.log(process.env.GITHUB_COMMIT_MESSAGE)

        transporter.sendMail({
          from: 'example@example.com',  
          to: 'recipient@example.com',   
          subject: 'GitHub Action Email',
          text: 'This is a test email sent from GitHub Actions using Nodemailer! <br> Cool'
        }, (err, info) => {
          if (err) {
            console.error(err);
          } else {
            console.log('Email sent: ' + info.response);
          }
        });
        "
