name: Hello World & Send Email on Push

on:
  push:
    branches:
      - main

jobs:
  say-hello:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Print Hello World message
        run: echo "Hello, World!"

  send-email:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Send Email via Mailtrap
        env:
          MAILTRAP_USERNAME: a6928cec736af1
          MAILTRAP_PASSWORD: 967757816e8c37
          MAILTRAP_HOST: sandbox.smtp.mailtrap.io
          MAILTRAP_PORT: 2525
        run: |
          echo "Installing msmtp..."
          sudo apt-get update && sudo apt-get install -y msmtp

          echo "Configuring msmtp for Mailtrap..."
          echo "defaults" > ~/.msmtprc
          echo "auth on" >> ~/.msmtprc
          echo "tls on" >> ~/.msmtprc
          echo "tls_starttls on" >> ~/.msmtprc
          echo "logfile ~/.msmtp.log" >> ~/.msmtprc
          echo "account mailtrap" >> ~/.msmtprc
          echo "host $MAILTRAP_HOST" >> ~/.msmtprc
          echo "port $MAILTRAP_PORT" >> ~/.msmtprc
          echo "user $MAILTRAP_USERNAME" >> ~/.msmtprc
          echo "password $MAILTRAP_PASSWORD" >> ~/.msmtprc
          echo "from sender@example.com" >> ~/.msmtprc
          echo "account default : mailtrap" >> ~/.msmtprc
          chmod 600 ~/.msmtprc

          echo "Sending test email..."
          echo "A new push has been made to the repository!" | msmtp -a mailtrap recipient@example.com

          echo "Email sent! Check msmtp log..."
          cat ~/.msmtp.log
