name: Hello World & Send Email on Push

on:
  push:
    branches:
      - main

jobs:
  say-hello:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Print Hello World message
        run: echo "Hello, World!"

  send-email:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Send Email via Mailtrap
        env:
          MAILTRAP_USERNAME: ${{ secrets.MAILTRAP_USERNAME }}
          MAILTRAP_PASSWORD: ${{ secrets.MAILTRAP_PASSWORD }}
          MAILTRAP_HOST: ${{ secrets.MAILTRAP_HOST }}
          MAILTRAP_PORT: ${{ secrets.MAILTRAP_PORT }}
        run: |
          echo "Sending email via Mailtrap"
          sudo apt-get update && sudo apt-get install -y ssmtp
          echo "root=postmaster" | sudo tee /etc/ssmtp/ssmtp.conf
          echo "mailhub=$MAILTRAP_HOST:$MAILTRAP_PORT" | sudo tee -a /etc/ssmtp/ssmtp.conf
          echo "AuthUser=$MAILTRAP_USERNAME" | sudo tee -a /etc/ssmtp/ssmtp.conf
          echo "AuthPass=$MAILTRAP_PASSWORD" | sudo tee -a /etc/ssmtp/ssmtp.conf
          echo "UseTLS=YES" | sudo tee -a /etc/ssmtp/ssmtp.conf
          echo "UseSTARTTLS=YES" | sudo tee -a /etc/ssmtp/ssmtp.conf
          echo "From: sender@example.com" > /tmp/email.txt
          echo "To: recipient@example.com" >> /tmp/email.txt
          echo "Subject: New Push Notification" >> /tmp/email.txt
          echo "A new push has been made to the repository!" >> /tmp/email.txt
          sudo ssmtp recipient@example.com < /tmp/email.txt
